line-length = 120
indent-width = 4

[lint]
# Enable pydocstyle (`D`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "D"]
preview = true

[lint.pycodestyle]
max-doc-length = 180
max-line-length = 120

[lint.pydocstyle]
convention = "google"

[format]
preview = true
exclude = ["*.pyi"]
docstring-code-format = true
quote-style = "single"